### ISSUE TITLE
Suppress the "Parcours Computer Science"

### ISSUE THREAD

**Issue by arnaud-m** [arnaud-m/master-info#67]

**Comment by maczinga** [comment]
Bonjour Arnaud,

Ca veut dire que le parcours CS n’existe plus ?

Vale,
 Enrico.

**Comment by arnaud-m** [comment]
Oui !
On a un seul pacours international/bilingue en M1.

**Comment by arnaud-m** [comment]
Add also link to EIT School : https://masterschool.eitdigital.eu/programmes/
